namespace GCDS.NetTemplate.Components
{
    /// <summary>
    /// Class holder for the header properties as defined in the GCDS template
    /// https://design-system.alpha.canada.ca/en/components/header/
    /// </summary>
    public class GcdsHeader : CommonProps
    {
        public enum SignatureVariantType
        {
            colour,
            white
        }

        /// <summary>
        /// Language toogle link
        /// Will be set inside the layout from the Template
        /// </summary>
        public string? LangHref { get; set; }

        /// <summary>
        /// Skip to main content href
        /// Will be set inside the layout based on a pre-defined const.
        /// </summary>
        public string? SkipToHref { get; set; }

        /// <summary>
        /// Remove the link to the Canada.ca homepage from the signature
        /// </summary>
        public bool SignatureHasLink { get; set; } = true;

        /// <summary>
        /// Switch the logo between color or all white
        /// </summary>
        public SignatureVariantType SignatureVariant { get; set; } = SignatureVariantType.colour;

        /// <summary>
        /// Add a custom partial that points to a banner to display above the header
        /// </summary>
        public CustomPartial? Banner { get; set; }

        /// <summary>
        /// Slot for the breadcrumbs
        /// </summary>
        public GcdsBreadcrumbs? Breadcrumb { get; set; }

        /// <summary>
        /// Slot for the Menu
        /// Either use the TopicMenu, the default menu that is generated by the template
        /// OR use the TopNav menu and create your own
        /// </summary>
        public ISlotHeaderMenu? Menu { get; set; }

        /// <summary>
        /// Add a search bar to the header
        /// An empty class 'new Search()' will create a default search bac that searches all of canada.ca
        /// </summary>
        public GcdsSearch? Search { get; set; }

        /// <summary>
        /// Override the skip-to main-content with either the custom SkipTo to quickly generate a skip link, or implement your own with CustomPartail
        /// </summary>
        public ISlotHeaderSkipTo? SkipToNav { get; set; }

        /// <summary>
        /// Override the default language toggle with a fully custom partial component
        /// </summary>
        public CustomPartial? Toggle { get; set; }
    }
}
