namespace GCDS.NetTemplate.Components
{
    public class Header : Common
    {
        //TODO Implement language toggle
        public string LangHref { get; set; } = "#";

        /// <summary>
        /// Remove the link to Canada.ca on the brand logo
        /// </summary>
        public bool SignatureHasLink { get; set; } = true;

        public enum SignatureVariantType
        {
            colour,
            white
        }
        /// <summary>
        /// Choose a white or colour signature (brand logo)
        /// colour by default
        /// </summary>
        public SignatureVariantType SignatureVariant { get; set; } = SignatureVariantType.colour;

        /// <summary>
        /// NOT IMPLEMENTED
        /// </summary>
        public string? Banner { get; set; }

        /// <summary>
        /// Add breadcrumbs bellow the header
        /// Canada.ca will be added to the breadcrumbs unless removed
        /// </summary>
        public Breadcrumbs? Breadcrumb { get; set; }

        /// <summary>
        /// Add a Menu to the header
        /// Either use the TopicMenu, the default menu that is generated by the template
        /// OR use the TopNav menu and create your own
        /// </summary>
        public IMenu? Menu { get; set; }

        /// <summary>
        /// Add a search bar to the header
        /// An empty class 'new Search()' will create a default search bac that searches all of canada.ca
        /// </summary>
        public Search? Search { get; set; }

        /// <summary>
        /// NOT VALIDATED
        /// </summary>
        public string? SkipToNav { get; set; }

        /// <summary>
        /// NOT VALIDATED
        /// </summary>
        public string? LangToggle { get; set; }
    }
}
