namespace GCDS.NetTemplate.Components.Gcds
{
    /// <summary>
    /// Class holder for the header properties as defined in the GCDS template
    /// https://design-system.alpha.canada.ca/en/components/header/
    /// </summary>
    public class Header : Common
    {
        public enum SignatureVariantType
        {
            colour,
            white
        }

        /// <summary>
        /// Language toogle link
        /// Will be set inside the layout from the Template
        /// </summary>
        public string? LangHref { get; set; }

        /// <summary>
        /// Skip to main content href
        /// Will be set inside the layout based on a pre-defined const.
        /// </summary>
        public string? SkipToHref { get; set; }

        /// <summary>
        /// Remove the link to the Canada.ca homepage from the signature
        /// </summary>
        public bool SignatureHasLink { get; set; } = true;

        /// <summary>
        /// Switch the logo between color or all white
        /// </summary>
        public SignatureVariantType SignatureVariant { get; set; } = SignatureVariantType.colour;

        /// <summary>
        /// NOT IMPLEMENTED
        /// </summary>
        [Obsolete("This slot is not implemented yet.")]
        public string? Banner { get; set; }

        /// <summary>
        /// Slot for the breadcrumbs
        /// </summary>
        public Breadcrumbs? Breadcrumb { get; set; }

        /// <summary>
        /// Slot for the Menu
        /// Either use the TopicMenu, the default menu that is generated by the template
        /// OR use the TopNav menu and create your own
        /// </summary>
        public IMenu? Menu { get; set; }

        /// <summary>
        /// Add a search bar to the header
        /// An empty class 'new Search()' will create a default search bac that searches all of canada.ca
        /// </summary>
        public Search? Search { get; set; }

        /// <summary>
        /// NOT IMPLEMENTED
        /// </summary>
        [Obsolete("This slot is not implemented yet.")]
        public string? SkipToNav { get; set; }

        /// <summary>
        /// NOT IMPLEMENTED
        /// </summary>
        [Obsolete("This slot is not implemented yet.")]
        public string? LangToggle { get; set; }
    }
}
